const insults = [
    "your mom gay lol",
    "Next time you want to talk shit on me, remember my postion in life and remember yours. I'm not some druggy piece of shit mf, I'm a fucking United States Marine. A title you will never claim. I've worked harder in the past 2 weeks than you ever have in your life. I have matured, learned, and taught myself to be independent while you're still living on your parents paychecks. I make my own money, I pay my own bills, I work on a fucking LAV25 while you can't even get a job at McDonald's. Don't ever try to talk down to me again because you were once above me because I will do nothing but strive to be on top and be better than the person I was yesterday. I've worked too hard and felt too much pain in my life for you to try and say you're better than me. Gtfo.",
    "Your mum on a tricycle.",
    "idiot.",
    "You are proof God makes mistakes.",
    "I dont hate you, but if you were on fire and I had water. I would drink it",
    "Some baby's were dropped on their head, but you were clearly thrown at a wall.",
    "You're lucky mirrors can't laugh",
    "What the fuck did you just fucking say about me, you little bitch? I’ll have you know I graduated top of my class in the Navy Seals, and I’ve been involved in numerous secret raids on Al-Quaeda, and I have over 300 confirmed kills. I am trained in gorilla warfare and I’m the top sniper in the entire US armed forces. You are nothing to me but just another target. I will wipe you the fuck out with precision the likes of which has never been seen before on this Earth, mark my fucking words. You think you can get away with saying that shit to me over the Internet? Think again, fucker. As we speak I am contacting my secret network of spies across the USA and your IP is being traced right now so you better prepare for the storm, maggot. The storm that wipes out the pathetic little thing you call your life. You’re fucking dead, kid. I can be anywhere, anytime, and I can kill you in over seven hundred ways, and that’s just with my bare hands. Not only am I extensively trained in unarmed combat, but I have access to the entire arsenal of the United States Marine Corps and I will use it to its full extent to wipe your miserable ass off the face of the continent, you little shit. If only you could have known what unholy retribution your little “clever” comment was about to bring down upon you, maybe you would have held your fucking tongue. But you couldn’t, you didn’t, and now you’re paying the price, you goddamn idiot. I will shit fury all over you and you will drown in it. You’re fucking dead, kiddo.",
    "You are swine you vulgar little maggot. Don\'t you know that you are pathetic? You worthless bag of filth. As we say in California, I\'ll bet you couldn\'t pour piss out of a boot with instructions on the heel. You are a canker. A sore that won\'t go away. A zit on the butt of society. I would rather kiss a lawyer than be seen with you.\n\nYou are a fiend and a coward, and you have bad breath. You are degenerate, noxious and depraved. I feel debased just for knowing you exist. I despise everything about you. You are a bloody nardless newbie twit protohominid chromosomally aberrant caricature of a coprophagic cloacal parasitic pond scum and I wish you would go away.\n\nYou\'re a putrescence mass, a walking vomit. You are a spineless little worm deserving nothing but the profoundest contempt. You are a stench, a revulsion, a big suck on a sour lemon.\n\nYou are a bleating fool, a curdled staggering mutant dwarf smeared richly with the effluvia and offal accompanying your alleged birth into this world. An insensate, blinking calf, meaningful to nobody, abandoned by the puke-drooling, giggling beasts who sired you and then killed themselves in recognition of what they had done.\n\nI will never get over the embarrassment of belonging to the same species as you. You are a monster, an ogre, a malformity. I barf at the very thought of you. You have all the appeal of a paper cut. Lepers avoid you. Because off your face the rabbit population actually decreased. You are vile, worthless, less than nothing. You are a weed, a fungus, the dregs of this earth. And did I mention you smell?\n\nIf you aren\'t an idiot, you made a world-class effort at simulating one.\n\nYou snail-skulled little rabbit. Would that a hawk pick you up, drive its beak into your brain, and upon finding it rancid set you loose to fly briefly before spattering the ocean rocks with the frothy pink shame of your ignoble blood. May you choke on the queasy, convulsing nausea of your own trite, foolish beliefs.",
    'Your birth certificate is an apology letter from the condom factory.',
    'I\'d like to see things from your point of view but I can\'t seem to get my head that far up my ass.',
    'You must have been born on a highway because that\'s where most accidents happen.',
    'Better to let people think you\'re smart until you open your mouth and prove them wrong.',
    'Is your ass jealous of the amount of shit that just came out of your mouth?',
    'You\'re so fat the only letters of the alphabet you know are KFC.',
    'Roses are red, violets are blue, I have 5 fingers, the 3rd ones for you.',
    'Your family tree must be a cactus because everybody on it is a prick.',
    'If I wanted to kill myself I\'d climb your ego and jump to your IQ.',
    'If laughter is the best medicine, your life must be curing the world.',
    'Did you eat paint chips when you were a kid?',
    'I\'m not saying I hate you, but I would unplug your life support to charge my phone.',
    'You\'re so ugly, when your mom dropped you off at school she got a fine for littering.',
    'Shock me, say something intelligent.',
    'I\'m jealous of all the people that haven\'t met you!.',
    'Don\'t feel sad, don\'t feel blue, Frankenstein was ugly too.',
    'I could eat a bowl of alphabet soup and shit out a smarter statement than that.',
    'I may love to shop but I\'m not buying your bullshit.',
    'Why don\'t you slip into something more comfortable -- like a coma.',
    'You look like something I\'d draw with my left hand.',
    'It\'s better to keep your mouth shut and give the \'impression\' that you\'re stupid than to open it and remove all doubt.',
    'It\'s too bad stupidity isn\'t painful.',
    'What\'s the difference between you and eggs? Eggs get laid and you don\'t.',
    'At least when I do a handstand my stomach doesn\'t hit me in the face.',
    'The last time I saw a face like yours I fed it a banana.',
    'If assholes could fly, this place would be an airport!',
    'You are so stupid, you\'d trip over a cordless phone.',
    'Hey, you have something on your chin... no, the 3rd one down.',
    'Ordinarily people live and learn. You just live.',
    'Aww, it\'s so cute when you try to talk about things you don\'t understand.',
    'If a crackhead saw you, he\'d think he needs to go on a diet.',
    'Learn from your parents\' mistakes - use birth control!',
    'When was the last time you could see your whole body in the mirror?',
    'I wish you no harm, but it would have been much better if you had never lived.',
    'If what you don\'t know can\'t hurt you, you\'re invulnerable.',
    'I heard you took an IQ test and they said your results were negative.',
    'If you had another brain, it would be lonely.',
    'You act like your arrogance is a virtue.',
    'We all sprang from apes, but you didn\'t spring far enough.',
    'You must think you\'re strong, but you only smell strong.',
    'Ever since I saw you in your family tree, I\'ve wanted to cut it down.',
    'If you spoke your mind, you\'d be speechless.',
    'Is your name Maple Syrup? It should be, you sap.',
    'Your mom must have a really loud bark!',
    'Why don\'t you let that hole under your nose heal up?',
    'For those who never forget a face, you are an exception.',
    'shut up ni-      ce guy'
]

module.exports = async function (msg, args) {
    const index = Math.floor(Math.random() * insults.length);
    msg.channel.send(insults[index])
}